### PR TITLE
Increase font-weight + remove unnecessary styles

### PR DESCRIPTION
**Pull request by JohJakob**
Increase font-weight of category buttons + remove unnecessary styles

### CODE REVIEW

**Comment by TJScalzo** [comment]
@JohJakob I'm not quite sure why you've done any of this... As far as I can see adding a `font-weight` changed nothing on the page. I _am_ running on a Mac and using Safari so it's possible that some other browser and/or OS needs the `font-weight` set to something.

The thing that I can't understand is why you removed those styles and said they were unnecessary. Those styles are what were making the category titles around the site be colored to match their category as well as change opacity when hovered. I don't quite understand why you'd want to remove them unless you wanted to make the titles not match their category color.

**Comment by TJScalzo** [comment]
Looking over the code I just noticed that `.post` sets the font-weight of everything to 300. I understand why you've done this now.

**Comment by JohJakob** [comment]
@TJScalzo Oh, I'm sorry. I thought the "unnecessary styles" were styles of your flexbox version. The category buttons have fairly high colors, so I increased the `font-weight` for better legibility.

**Comment by TJScalzo** [comment]
@JohJakob Should I increase the font-weight myself or do you want to make another pull request?

**Comment by JohJakob** [comment]
@TJScalzo Yes, you can change it.

**Pull request closed without merging**
