### PR TITLE
shorter, faster, larger, smaller

### PR DESCRIPTION
**Pull request by Haroenv**
a different gif (2MB)

### CODE REVIEW

**Comment by TJScalzo** [comment]
@Haroenv This looks awesome! One tiny thing: Is it possible to slow down what's happening? Everything seems to be happening very fast. If not this gif is great, I just want to know if it can be even better.

**Comment by Haroenv** [comment]
Yes, it can be slowed down a bit, currently it's sped up

**Comment by TJScalzo** [comment]
@Haroenv If you could post a slowed down version I think that'd work better.

**Comment by Haroenv** [comment]
Okay, hang on!

**Comment by Haroenv** [comment]
I added the second version, it's slower (130% of recorded speed vs 200%), so now it's 10s. It's also smaller (560px wide vs 900px wide) and thus 700kb instead of 2mb

**Comment by TJScalzo** [comment]
@Haroenv The slower version is great. I again have one question: Can you go inside of a post and scroll to the bottom to show that the category is listed there?

**Comment by Haroenv** [comment]
I can do that, just have to take a new screengrab, since in that one it got cropped out accidentally

**Comment by TJScalzo** [comment]
@Haroenv, thank you. That would be wonderful!

**Comment by Haroenv** [comment]
What do you think of this version @TJScalzo ?

**Comment by TJScalzo** [comment]
@Haroenv That looks perfect! I'll merge these changes and then delete the other gifs. Thank you for doing this. I'm very excited to have completely finished this!

**Comment by Haroenv** [comment]
Well, I'm glad I can help

**Pull request merged**
